GET http://localhost:8000/assets/bases

###

GET http://localhost:8000/assets/ingredients

###

GET http://localhost:8000/assets/proteins

###

GET http://localhost:8012/assets/portions

###

POST http://localhost:8012/api/login
Content-Type: application/json

{
  "username": "aze",
  "password": "password"
}

###

POST http://localhost:8000/poke
Content-Type: application/json

{
  "base_id": 1,
  "price": 3,
  "ingredient_ids": [
    1,
    2,
    2
  ],
  "portion_id": 1,
  "protein_ids": [
    1,
    2
  ]
}

###

POST http://localhost:8000/order
Content-Type: application/json

{
  "poke_ids": [
    1,
    2
  ]
}